version: '3.1'

services:
  invest-bag-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: invest-bag-db
    depends_on:
      - invest-bag-db