### Send get request 
GET http://0.0.0.0:9090/api/positions?rubUsd=73.71&rubEvro=89.3325

### Add position
POST http://0.0.0.0:9090/api/position/add
Content-Type: application/json

{
  "tiker": "TEUR",
  "name": "Тинькофф Вечный портфель EUR",
  "type": "Облигация",
  "count": 10,
  "price": 0.1036,
  "currency": "euro"
}

### Del position
POST http://0.0.0.0:9090/api/position/del
Content-Type: application/json

{
  "tiker": "TSPX",
  "name": "Тинькофф S&P 500",
  "type": "Облигация",
  "count": 1,
  "price": 0.1001,
  "currency": "usd"
}