### Send get request 
GET http://0.0.0.0:9090/api/position

### Send post request 
POST http://0.0.0.0:9090/api/position
Content-Type: application/json

{
  "tiker": "TCSG",
  "name": "TCS Group",
  "type": "Акция",
  "count": 20,
  "price": 3228.2,
  "currency": "RUB"
}
